### ISSUE TITLE
Temp code in master

### ISSUE THREAD

**Issue by nathanielc** [gl91306/launcherpi#6]
See https://github.com/gl91306/launcherpi/blob/main/index.js#L192

I'd like to help test this, however I was unable to get it working. I traced the issue to this temp code still committed that hard codes the profile etc. I tried tweaking this code to be specific to my env but only hit more issues after that.

**Comment by gl91306** [comment]
oop, didnt realize i left that there :P. Ill fix it when i get home

**Comment by gl91306** [comment]
i added a thing to fix it, if it dont work then plz sned a videeo of it not working plus console log

**Comment by gl91306** [comment]
closing as it seems to be fixed
