### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by rishireddy1599** [gl91306/launcherpi#7]
the software doesn't compile on my raspberry pi 4

**Comment by gl91306** [comment]
pls paste the compile error

**Comment by gl91306** [comment]
plz repsond

**Comment by ghost** [comment]
I'll need a second

**Comment by ghost** [comment]
![Screenshot 2022-09-22 183505](https://user-images.githubusercontent.com/69160188/191863159-0fe31955-d418-4717-b167-4d69019b0f3c.png)

**Comment by ghost** [comment]
this is the problem, i also did npm fund

**Comment by gl91306** [comment]
whyd u do npm fund? also u didnt do npm start. try deleting the folder and re clone.

**Comment by gl91306** [comment]
bruh ok i geuss its completed
